-- Create table tb_food_item
CREATE TABLE tb_food_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(50) NOT NULL,
    quantity INT NOT NULL,
    validity DATE  NOT NULL
);